comment:
  layout: "header, diff, components"

component_management:
  individual_components:
    - component_id: genflow-ui
      name: genflow-ui
      paths:
        - genflow-ui/**
    - component_id: genflow-server
      name: genflow-server
      paths:
        - genflow/**

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  status:
    patch: false
    project:
      default:
        target: auto
        threshold: 5%