# Copyright (C) 2025 Reveal AI
#
# SPDX-License-Identifier: MIT

FROM node:lts-slim AS gen_flow-ui

ENV TERM=xterm \
    LANG="C.UTF-8"  \
    LC_ALL="C.UTF-8"

# Install dependencies
COPY package.json /tmp/
COPY yarn.lock /tmp/
COPY gen_flow-ui/package.json /tmp/gen_flow-ui/

# Install common dependencies
WORKDIR /tmp/
RUN DISABLE_HUSKY=1 yarn --frozen-lockfile

# Build source code
COPY gen_flow-ui/ /tmp/gen_flow-ui/
RUN yarn run build:gen_flow-ui

FROM nginx:1.27.4-alpine3.21-slim

# Replace default.conf configuration to remove unnecessary rules
COPY gen_flow-ui/react_nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=gen_flow-ui /tmp/gen_flow-ui/build /usr/share/nginx/html/
