# Copyright (C) 2025 Reveal AI
#
# Licensed under the Apache License, Version 2.0 with Additional Commercial Terms.

services:
  genflow_db:
    ports:
      - '5432:5432'

  genflow_server:
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        socks_proxy:
        CLAM_AV:
        GF_DEBUG_ENABLED:
        COVERAGE_PROCESS_START:
    environment:
      # Use this with GF_DEBUG_ENABLED to avoid server response timeouts
      GF_DEBUG_ENABLED: '${GF_DEBUG_ENABLED:-no}'
      GF_DEBUG_PORT: '9090'
      # If 'yes', wait for a debugger connection on startup
      GF_DEBUG_WAIT: '${GF_DEBUG_WAIT_CLIENT:-no}'
      COVERAGE_PROCESS_START:
    ports:
      - '9090:9090'

  genflow_ui:
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
      dockerfile: Dockerfile.ui