# Copyright (C) 2025 Reveal AI
#
# Licensed under the Apache License, Version 2.0 with Additional Commercial Terms.

FROM geniflow/server:local

ENV DJANGO_SETTINGS_MODULE=geniflow.settings.testing
USER root

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -yq \
        build-essential \
        python3-dev \
        && \
    rm -rf /var/lib/apt/lists/*;

COPY geniflow/requirements/ /tmp/geniflow/requirements/

RUN python3 -m ensurepip
RUN python3 -m pip install --no-cache-dir -r /tmp/geniflow/requirements/testing.txt

COPY .coveragerc .

ENTRYPOINT []