# Copyright (C) 2025 Reveal AI
#
# Licensed under the Apache License, Version 2.0 with Additional Commercial Terms.

FROM node:lts-slim AS genflow-ui

ENV TERM=xterm \
    LANG="C.UTF-8"  \
    LC_ALL="C.UTF-8"

# Install dependencies
COPY package.json /tmp/
COPY yarn.lock /tmp/
COPY genflow-ui/package.json /tmp/genflow-ui/

# Install common dependencies
WORKDIR /tmp/
RUN DISABLE_HUSKY=1 yarn --frozen-lockfile

# Build source code
COPY genflow-ui/ /tmp/genflow-ui/
RUN yarn run build:genflow-ui

FROM nginx:1.27.4-alpine3.21-slim

# Replace default.conf configuration to remove unnecessary rules
COPY genflow-ui/react_nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=genflow-ui /tmp/genflow-ui/build /usr/share/nginx/html/
