[tool.isort]
profile = "black"
forced_separate = ["tests"]
line_length = 100
skip_gitignore = true # align tool behavior with Black
extend_skip=[]

[tool.black]
line-length = 100
target-version = ['py39']
extend-exclude = """
"""