baseURL = '/'
languageCode = 'en-us'
title = 'GenFlow'
theme = 'docsy'

# Language settings
defaultContentLanguage = 'en'
enableMissingTranslationPlaceholders = true
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 10

# Top menu
[[menu.main]]
    name = "Try it now"
    weight = 3
    url = "https://demo.genflow.revealai.de"
[[menu.main]]
    name = "GitHub"
    weight = 4
    url = "https://github.com/Reveal-AI-DE/GenFlow"
    pre = "<i class='fab fa-github'></i>"

# Image processing configuration.
[imaging]
    resampleFilter = "CatmullRom"
    quality = 75
    anchor = "smart"

[services]
[services.googleAnalytics]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

[params.ui]
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact = true
    ul_show = 2
    #  Set to true to disable breadcrumb navigation.
    breadcrumb_disable = false
    #  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
    sidebar_search_disable = false
    #  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
    navbar_logo = true
    # Set to true to disable the About link in the site footer
    footer_about_disable = true