# Generated by Django 5.1.6 on 2025-04-03 15:40

import django.db.models.deletion
import gen_flow.apps.prompt.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=9)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='team.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pre_prompt', models.TextField()),
                ('suggested_questions', models.JSONField(null=True)),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('advanced', 'Advanced')], default='simple', max_length=10)),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published')], default='drafted', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=gen_flow.apps.prompt.models.get_prompt_media_path)),
                ('related_test_session', models.IntegerField(null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('related_model', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.providermodelconfig')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='team.team')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompt.promptgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
