# Generated by Django 5.1.6 on 2025-04-03 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('prompt', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('session_type', models.CharField(choices=[('llm', 'Llm'), ('prompt', 'Prompt')], default='llm', max_length=10)),
                ('session_mode', models.CharField(choices=[('chat', 'Chat'), ('completion', 'Completion')], default='chat', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('related_model', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.providermodelconfig')),
                ('related_prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompt.prompt')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='team.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('query', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='team.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
