id: chatgpt-4o-latest
label:
  en_US: chatgpt-4o-latest
  de_DE: chatgpt-4o-aktuell
type: llm
features:
  - multi-tool-call
  - agent-thought
  - stream-tool-call
  - vision
properties:
  mode: chat
  context_size: 128000
parameter_configs:
  - name: temperature
    use_template: temperature
  - name: top_p
    use_template: top_p
  - name: presence_penalty
    use_template: presence_penalty
  - name: frequency_penalty
    use_template: frequency_penalty
  - name: max_tokens
    use_template: max_tokens
    default: 512
    min: 1
    max: 16384
    advanced: false
pricing:
  input: '2.50'
  output: '10.00'
  unit: '0.000001'
  currency: USD
