id: gpt-3.5-turbo
label:
  en_US: gpt-3.5-turbo
  de_DE: gpt-3.5-turbo
type: llm
features:
  - multi-tool-call
  - agent-thought
  - stream-tool-call
properties:
  mode: chat
  context_size: 16385
parameter_configs:
  - name: temperature
    use_template: temperature
  - name: top_p
    use_template: top_p
  - name: presence_penalty
    use_template: presence_penalty
  - name: frequency_penalty
    use_template: frequency_penalty
  - name: max_tokens
    use_template: max_tokens
    default: 512
    min: 1
    max: 4096
pricing:
  input: '0.0005'
  output: '0.0015'
  unit: '0.001'
  currency: USD
