id: gpt-4-vision-preview
label:
  en_US: gpt-4-vision-preview
  de_DE: gpt-4-vision-preview
type: llm
features:
  - vision
properties:
  mode: chat
  context_size: 128000
parameter_configs:
  - name: temperature
    use_template: temperature
  - name: top_p
    use_template: top_p
  - name: presence_penalty
    use_template: presence_penalty
  - name: frequency_penalty
    use_template: frequency_penalty
  - name: max_tokens
    use_template: max_tokens
    default: 512
    min: 1
    max: 4096
    advanced: false
  - name: seed
    label:
      en_US: Seed
    type: int
    help:
      en_US: If specified, model will make a best effort to sample deterministically,
        such that repeated requests with the same seed and parameters should return
        the same result. Determinism is not guaranteed, and you should refer to the
        system_fingerprint response parameter to monitor changes in the backend.
    required: false
    advanced: true
pricing:
  input: '0.01'
  output: '0.03'
  unit: '0.001'
  currency: USD
