id: gpt-4o-mini
label:
  en_US: gpt-4o-mini
  de_DE: gpt-4o-mini
type: llm
features:
  - multi-tool-call
  - agent-thought
  - stream-tool-call
  - vision
properties:
  mode: chat
  context_size: 128000
parameter_configs:
  - name: temperature
    use_template: temperature
  - name: top_p
    use_template: top_p
  - name: presence_penalty
    use_template: presence_penalty
  - name: frequency_penalty
    use_template: frequency_penalty
  - name: max_tokens
    use_template: max_tokens
    type: int
    default: 512
    min: 1
    max: 16384
    advanced: false
pricing:
  input: '0.15'
  output: '0.60'
  unit: '0.000001'
  currency: USD
