id: o1-mini
label:
  en_US: o1-mini
  de_DE: o1-mini
type: llm
features:
  - agent-thought
properties:
  mode: chat
  context_size: 128000
parameter_configs:
  - name: max_tokens
    use_template: max_tokens
    default: 65536
    min: 1
    max: 65536
    advanced: false
pricing:
  input: '3.00'
  output: '12.00'
  unit: '0.000001'
  currency: USD
