name: Docs
on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate_github_pages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.123.7/hugo_extended_0.123.7_Linux-64bit.tar.gz
          (mkdir hugo && tar -xf hugo_extended_0.123.7_Linux-64bit.tar.gz -C hugo)

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install npm packages
        working-directory: ./site
        run: |
          npm ci

      - name: Build docs
        run: |
          pip install -r site/requirements.txt
          PATH="$PWD/hugo:$PATH" python site/build.py
        env:
          HUGO_ENV: production

      - name: Deploy
        if: github.ref == 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: docs.genflow.revealai.de
